// ── Conversation messages ──────────────────────────────────
const conversations = {
  'Caroline Brennan': [
    { da: { type: 'ticket-created', date: 'October 24', name: 'Caroline Brennan' } },
    { dir:'out', text:'Welcome to Clarity! How can we help you today?', time:'14:24' },
    { dir:'in',  text:'Hi. How can I top up with apple pay?', time:'14:25' },
    { da: { type: 'assign-to', name: 'Jamie Wilson' } },
    { dir:'out', text:'Of course! You can top up via Apple Pay by going to Settings → Payment Methods → Add New. It should appear as an option if your device supports it.', time:'14:26' },
    { dir:'in',  text:'I don\'t see it on my device', time:'14:27' },
    { da: { type: 'priority', priority: 'critical' } },
    { dir:'out', text:'Could you let me know which device and iOS version you\'re on? That will help us investigate further.', time:'14:28' },
    { dir:'in',  text:'iPhone 14, iOS 17.2', time:'14:29' },
    { dir:'out', text:'Thanks! That version is fully supported. Could you try force-closing the app and reopening it? Sometimes the payment options need a refresh.', time:'14:30' },
  ],
  'Ethan Kim': [
    { da: { type: 'ticket-created', date: 'October 24', name: 'Ethan Kim' } },
    { dir:'out', text:'Hi Ethan! How can we assist you today?', time:'09:10' },
    { dir:'in',  text:'Can I use multiple payment methods for a single transaction?', time:'09:11' },
    { da: { type: 'assign-to', name: 'Marcus Taylor' } },
    { dir:'out', text:'Unfortunately, we currently only support one payment method per transaction. However, you can split payments by making two separate top-ups.', time:'09:13' },
    { dir:'in',  text:'That\'s a bit inconvenient. Is this something you plan to support?', time:'09:15' },
    { dir:'out', text:'Absolutely, it\'s on our roadmap! We\'ll notify you as soon as it\'s available. Is there anything else I can help with?', time:'09:16' },
  ],
  'Jason Lee': [
    { da: { type: 'ticket-created', date: 'October 23', name: 'Jason Lee' } },
    { dir:'out', text:'Hello Jason, welcome! What brings you in today?', time:'08:00' },
    { dir:'in',  text:'What\'s the best way to contact support if this chat isn\'t available?', time:'08:02' },
    { dir:'out', text:'You can reach us at support@clarity.com or call +1 800 123 4567. We\'re available 24/7.', time:'08:03' },
    { dir:'in',  text:'Great, and what\'s the typical response time for email?', time:'08:04' },
    { dir:'out', text:'Usually within 2 hours during business hours, and up to 6 hours on weekends.', time:'08:05' },
    { dir:'in',  text:'Perfect, thanks!', time:'08:06' },
    { da: { type: 'change-status', status: 'Closed', color: '#87888a' } },
  ],
  'Aisha Patel': [
    { da: { type: 'ticket-created', date: 'October 23', name: 'Aisha Patel' } },
    { da: { type: 'not-assigned' } },
    { dir:'out', text:'Hi Aisha! How can I help you today?', time:'11:30' },
    { dir:'in',  text:'Can you help me with my account verification? I submitted my ID 3 days ago.', time:'11:31' },
    { da: { type: 'assign-to', name: 'Emma Davis' } },
    { dir:'out', text:'I\'m looking into it now. I can see your documents were received on Monday. The review team typically takes 3–5 business days.', time:'11:33' },
    { dir:'in',  text:'Okay, so it might be done today or tomorrow?', time:'11:34' },
    { dir:'out', text:'That\'s correct! You\'ll receive a confirmation email as soon as it\'s approved.', time:'11:35' },
  ],
  'Marcus Wu': [
    { da: { type: 'ticket-created', date: 'October 22', name: 'Marcus Wu' } },
    { dir:'out', text:'Hey Marcus, what can we do for you today?', time:'10:00' },
    { dir:'in',  text:'Is there a way to change my subscription plan?', time:'10:01' },
    { dir:'out', text:'Yes! Head to Account → Subscription → Change Plan. You can upgrade or downgrade anytime.', time:'10:02' },
    { dir:'in',  text:'Will I lose any credits if I downgrade?', time:'10:03' },
    { da: { type: 'snooze-started', until: 'Tomorrow 10:00' } },
    { dir:'out', text:'No credits will be lost. Any unused balance carries over to your new plan.', time:'10:04' },
    { dir:'in',  text:'Nice. What about billing — will it be prorated?', time:'10:05' },
    { dir:'out', text:'Yes, billing is prorated. You\'ll only be charged for the remaining days on your new plan.', time:'10:07' },
  ],
  'Linda Gomez': [
    { dir:'out', text:'Hi Linda! What can I help you with?', time:'15:00' },
    { dir:'in',  text:'How do I reset my password?', time:'15:01' },
    { dir:'out', text:'Easy! Go to the login page and click "Forgot Password". You\'ll receive a reset link in your email within 1–2 minutes.', time:'15:02' },
    { dir:'in',  text:'I didn\'t get the email', time:'15:05' },
    { dir:'out', text:'Please check your spam/junk folder. If it\'s not there, I can resend it manually. What email address should I use?', time:'15:06' },
  ],
  'Carlos Rodriguez': [
    { da: { type: 'ticket-created', date: 'October 21', name: 'Carlos Rodriguez' } },
    { dir:'out', text:'Hello Carlos! How can we help?', time:'13:00' },
    { dir:'in',  text:'What security measures do you have to protect my data?', time:'13:01' },
    { da: { type: 'reassigned', from: 'Sofia Almeida', to: 'David Park' } },
    { dir:'out', text:'We use AES-256 encryption at rest and TLS 1.3 in transit. All data is stored in ISO 27001 certified data centers.', time:'13:02' },
    { dir:'in',  text:'Do you share data with third parties?', time:'13:03' },
    { dir:'out', text:'Only with your explicit consent. You can review and manage your data sharing preferences in Account → Privacy.', time:'13:05' },
  ],
  'Julia Chen': [
    { dir:'out', text:'Hi Julia, what brings you here today?', time:'09:45' },
    { dir:'in',  text:'How do I report a technical issue with the app?', time:'09:46' },
    { dir:'out', text:'You can report issues directly from the app: tap Help → Report a Problem. Screenshots and logs are automatically attached.', time:'09:47' },
    { dir:'in',  text:'What if the app won\'t open at all?', time:'09:48' },
    { dir:'out', text:'In that case, email us at bugs@clarity.com with your device model and OS version. We\'ll prioritize it.', time:'09:50' },
  ],
  'Brandon Smith': [
    { dir:'out', text:'Hey Brandon! What can I help you with today?', time:'14:10' },
    { dir:'in',  text:'What features are included in the free trial?', time:'14:11' },
    { dir:'out', text:'The free trial includes all Pro features for 14 days — unlimited transactions, analytics, multi-currency support, and priority support.', time:'14:12' },
    { dir:'in',  text:'Do I need a credit card to sign up?', time:'14:13' },
    { dir:'out', text:'No credit card needed! You can sign up with just your email. We\'ll only ask for payment if you choose to upgrade after the trial.', time:'14:14' },
  ],
  'Nina Brown': [
    { dir:'out', text:'Hi Nina! What can we help you with?', time:'16:30' },
    { dir:'in',  text:'Can I change my email address linked to the account?', time:'16:31' },
    { dir:'out', text:'Yes! Go to Account → Profile → Email Address. You\'ll need to verify both the old and new email addresses.', time:'16:32' },
    { dir:'in',  text:'I no longer have access to my old email', time:'16:33' },
    { dir:'out', text:'No problem. I can bypass that by verifying your identity with your phone number or ID. Would you like to proceed?', time:'16:35' },
  ],
  'Oliver Johnson': [
    { dir:'out', text:'Hello Oliver! How can I assist?', time:'11:00' },
    { dir:'in',  text:'How do I contact customer service directly?', time:'11:01' },
    { dir:'out', text:'You can reach us here on live chat (24/7), by phone at +1 800 123 4567, or by email at support@clarity.com.', time:'11:02' },
    { dir:'in',  text:'Is there a dedicated account manager for business accounts?', time:'11:03' },
    { dir:'out', text:'Yes! Business and Enterprise plans include a dedicated account manager. Would you like to know more about upgrading?', time:'11:05' },
  ],
  'Grace White': [
    { dir:'out', text:'Hi Grace! What can I do for you?', time:'10:20' },
    { dir:'in',  text:'What should I do if I forget my username?', time:'10:21' },
    { dir:'out', text:'Your username is usually your email address. Try logging in with the email you used to register.', time:'10:22' },
    { dir:'in',  text:'I tried that but it says account not found', time:'10:23' },
    { dir:'out', text:'You might have registered with a different email. I can look you up by phone number if you have one on file — would that help?', time:'10:24' },
  ],
  'Leo Thompson': [
    { dir:'out', text:'Hey Leo! How can we help today?', time:'17:00' },
    { dir:'in',  text:'Are there any promotions or discounts available right now?', time:'17:01' },
    { dir:'out', text:'We have an ongoing 20% discount on annual plans this month! Use code CLARITY20 at checkout.', time:'17:02' },
    { dir:'in',  text:'Does that apply to upgrades too?', time:'17:03' },
    { dir:'out', text:'Yes, it applies to new subscriptions and upgrades. It expires on the 30th of this month.', time:'17:04' },
    { dir:'in',  text:'Perfect, I\'ll upgrade now. Thanks!', time:'17:05' },
  ],
  'Emma Garcia': [
    { dir:'out', text:'Hi Emma! How can I assist you today?', time:'08:30' },
    { dir:'in',  text:'What are your returns policy options?', time:'08:31' },
    { dir:'out', text:'We offer a 30-day money-back guarantee on all paid plans, no questions asked. Just cancel within 30 days of purchase.', time:'08:32' },
    { dir:'in',  text:'And what if I was charged twice by mistake?', time:'08:33' },
    { dir:'out', text:'That would be refunded immediately. If you\'ve noticed a duplicate charge, I can look into it right now — can you share your account email?', time:'08:35' },
  ],
  'Liam Johnson': [
    { dir:'out', text:'Hello Liam! What can I help you with?', time:'12:00' },
    { dir:'in',  text:'How can I track my order?', time:'12:01' },
    { dir:'out', text:'You can track your order under Account → Orders → Track. You\'ll also receive email updates at each stage.', time:'12:02' },
    { dir:'in',  text:'I haven\'t received any emails', time:'12:03' },
    { dir:'out', text:'Let me check your notification settings. Could you confirm if marketing/transactional emails are enabled in your account preferences?', time:'12:05' },
    { dir:'in',  text:'They seem to be on', time:'12:06' },
    { dir:'out', text:'I\'ll resend the tracking email now. Please check your inbox in the next few minutes.', time:'12:07' },
  ],
};

// ── Channel icons ──────────────────────────────────────────
const CH = {
  livechat: `<img src="icons/12px/LiveChat.svg" width="12" height="12" alt="LiveChat"/>`,
  whatsapp: `<img src="icons/12px/Whatsapp.svg" width="12" height="12" alt="WhatsApp"/>`,
  android:  `<img src="icons/12px/Android.svg"  width="12" height="12" alt="Android"/>`,
  apple:    `<img src="icons/12px/Apple.svg"    width="12" height="12" alt="Apple"/>`,
};

// ── Inbox conversations ────────────────────────────────────
const allConversations = [
  { name:'Caroline Brennan', initials:'CB', bg:'var(--utilities-surface-orangesubtle)', color:'var(--utilities-content-onsoft-orange)', ch:'livechat', time:'13min', preview:'Hi. How can I top up with apple pay?',           badge:0, views:['assigned','all'] },
  { name:'Ethan Kim',        initials:'EK', bg:'var(--utilities-surface-cyansubtle)',   color:'var(--utilities-content-onsoft-cyan)',   ch:'whatsapp', time:'2h',   preview:'Can I use multiple payment methods?',             badge:1, views:['assigned','all'] },
  { name:'Jason Lee',        initials:'JL', bg:'var(--utilities-surface-bluesubtle)',   color:'var(--utilities-content-onsoft-blue)',   ch:'whatsapp', time:'6h',   preview:"What's the best way to contact support?",         badge:2, views:['assigned','all'] },
  { name:'Aisha Patel',      initials:'AP', bg:'var(--utilities-surface-pinksubtle)',   color:'var(--utilities-content-onsoft-pink)',   ch:'livechat', time:'1d',   preview:'Can you help me with my account verification?',   badge:0, views:['assigned','all'] },
  { name:'Marcus Wu',        initials:'MW', bg:'var(--utilities-surface-cyansubtle)',   color:'var(--utilities-content-onsoft-cyan)',   ch:'android',  time:'1d',   preview:'Is there a way to change my subscription?',       badge:4, views:['unassigned','all'] },
  { name:'Linda Gomez',      initials:'LG', bg:'var(--utilities-surface-orangesubtle)', color:'var(--utilities-content-onsoft-orange)', ch:'livechat', time:'1d',   preview:'How do I reset my password?',                     badge:0, quote:true, views:['mentions','all'] },
  { name:'Carlos Rodriguez', initials:'CR', bg:'var(--utilities-surface-purplesubtle)', color:'var(--utilities-content-onsoft-purple)', ch:'livechat', time:'2d',   preview:'What are the security measures for my data?',     badge:0, views:['snoozed','all'] },
  { name:'Julia Chen',       initials:'JC', bg:'var(--utilities-surface-purplesubtle)', color:'var(--utilities-content-onsoft-purple)', ch:'livechat', time:'2d',   preview:'How to report a technical issue?',                badge:0, views:['unassigned','all'] },
  { name:'Brandon Smith',    initials:'BS', bg:'var(--utilities-surface-bluesubtle)',   color:'var(--utilities-content-onsoft-blue)',   ch:'livechat', time:'2d',   preview:'What features are included in the free trial?',   badge:0, views:['mentions','all'] },
  { name:'Nina Brown',       initials:'NB', bg:'var(--utilities-surface-pinksubtle)',   color:'var(--utilities-content-onsoft-pink)',   ch:'android',  time:'3d',   preview:'Can I change my email address linked to...',      badge:0, views:['snoozed','all'] },
  { name:'Oliver Johnson',   initials:'OJ', bg:'var(--utilities-surface-orangesubtle)', color:'var(--utilities-content-onsoft-orange)', ch:'android',  time:'3d',   preview:'How do I contact customer service directly?',     badge:0, quote:true, views:['unassigned','all'] },
  { name:'Grace White',      initials:'GW', bg:'var(--utilities-surface-cyansubtle)',   color:'var(--utilities-content-onsoft-cyan)',   ch:'android',  time:'4d',   preview:'What should I do if I forget my username?',       badge:0, views:['closed','all'] },
  { name:'Leo Thompson',     initials:'LT', bg:'var(--utilities-surface-purplesubtle)', color:'var(--utilities-content-onsoft-purple)', ch:'livechat', time:'4d',   preview:'Are there any promotions available right now?',   badge:0, views:['closed','all'] },
  { name:'Emma Garcia',      initials:'EG', bg:'var(--utilities-surface-pinksubtle)',   color:'var(--utilities-content-onsoft-pink)',   ch:'whatsapp', time:'4d',   preview:'What are the returns policy options?',            badge:0, views:['mentions','all'] },
  { name:'Liam Johnson',     initials:'LJ', bg:'var(--utilities-surface-bluesubtle)',   color:'var(--utilities-content-onsoft-blue)',   ch:'livechat', time:'4d',   preview:'How can I track my order?',                       badge:0, views:['closed','all'] },
];

// ── Copilot data ───────────────────────────────────────────
const copilotData = {
  'Caroline Brennan': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer wants to reschedule a loan payment.',
    intent: 'Loan Payment Reschedule.',
    facts: 'Next payment 1,950 SAR due Nov 15; 3-day grace; 2% late fee after grace.',
    policy: 'One-time reschedule up to 7 days; supervisor approval likely (last payment slightly delayed).',
    sentiment: 'Concern → neutral.',
    tip: 'Customer meets 3/4 conditions.<br>Eligible if manual override approved.',
    reply1: 'Hi Sara, I am Fatimah and I\'ll try to help you.<br>I can confirm your reschedule request. Let me check your eligibility quickly.',
    action: 'Customer wants to reschedule payment. Do you want me to reschedule to Nov 20?',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'Thank you, Sarah. Your payment has been rescheduled for November 20, 2025.<br><br>You will retain your 3-day grace period.<br><br>Can I help you with anything else today?',
  },
  'Ethan Kim': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer asking about split payments across multiple methods.',
    intent: 'Payment Method Query.',
    facts: 'User wants to use multiple payment methods in one transaction. Workaround: two separate top-ups.',
    policy: 'Currently one payment method per transaction. Feature is on the roadmap.',
    sentiment: 'Neutral → mild frustration.',
    tip: 'Feature is on the roadmap. Offer workaround and notify when available.',
    reply1: 'Hi Ethan! You can\'t split a single transaction right now, but two top-ups work as a workaround.',
    action: 'Add customer to notification list for multi-payment feature launch.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'Great news — this feature is on our roadmap and you\'ll be among the first to know!<br><br>In the meantime, two separate top-ups will achieve the same result.<br><br>Is there anything else I can help with?',
  },
  'Jason Lee': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer asking about alternative support contact options.',
    intent: 'Support Contact Information.',
    facts: 'Customer wants alternatives if live chat is unavailable. Email response: 2h business hours, 6h weekends.',
    policy: 'Support available 24/7 via email and phone.',
    sentiment: 'Neutral → satisfied.',
    tip: 'Standard info request. Provide all contact channels proactively.',
    reply1: 'Hi Jason! You can always reach us at support@clarity.com or +1 800 123 4567, available 24/7.',
    action: 'Log contact details request for self-service article improvement.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'You\'re all set, Jason! Here\'s a summary of our contact options:<br><br>📧 support@clarity.com (2h response)<br>📞 +1 800 123 4567 (24/7)<br>💬 Live chat: whenever we\'re online<br><br>Happy to help anytime!',
  },
  'Aisha Patel': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer checking status of ID verification submitted 3 days ago.',
    intent: 'Account Verification Status.',
    facts: 'Documents received Monday. Review SLA is 3–5 business days.',
    policy: 'Verification reviews take 3–5 business days. Confirmation email sent upon approval.',
    sentiment: 'Mild concern → reassured.',
    tip: 'Within normal SLA. Reassure and flag for priority if not resolved by tomorrow.',
    reply1: 'Hi Aisha! Your documents were received on Monday — review typically takes 3–5 business days.',
    action: 'Flag for priority review if not resolved by end of day.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'Good news, Aisha — your verification is progressing normally.<br><br>Based on the submission date, expect a confirmation email today or tomorrow.<br><br>Let me know if you haven\'t heard back by end of day!',
  },
  'Marcus Wu': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer wants to downgrade subscription and asking about credits and billing.',
    intent: 'Subscription Plan Change.',
    facts: 'Customer wants to downgrade. Concerned about losing credits and billing proration.',
    policy: 'No credit loss on plan changes. Billing is prorated. Changes effective immediately.',
    sentiment: 'Curious → satisfied.',
    tip: 'Straightforward downgrade. Confirm no credit loss and proration policy.',
    reply1: 'Hi Marcus! Good news — no credits are lost when you change plans, and billing is prorated.',
    action: 'Initiate plan change request if customer confirms.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'You\'re all set to downgrade, Marcus!<br><br>✅ No credits lost — your balance carries over.<br>✅ Billing is prorated for remaining days.<br><br>Go to Account → Subscription → Change Plan whenever you\'re ready!',
  },
  'Linda Gomez': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer did not receive password reset email.',
    intent: 'Password Reset — Email Not Received.',
    facts: 'Reset email not received. Spam folder not checked. May need manual resend.',
    policy: 'Reset links expire after 30 minutes. Agent can manually resend to verified address.',
    sentiment: 'Frustrated → pending.',
    tip: 'Check spam first. If not found, manually resend to the email on file.',
    reply1: 'Hi Linda! Let\'s check your spam folder first — if it\'s not there, I\'ll resend the link right away.',
    action: 'Resend password reset email to verified address on file.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'I\'ve just resent the password reset link to your email address.<br><br>It should arrive within 1–2 minutes. Please also check your spam folder.<br><br>Let me know if you\'re still having trouble!',
  },
  'Carlos Rodriguez': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer asking about data security measures and third-party data sharing.',
    intent: 'Data Security & Privacy.',
    facts: 'AES-256 at rest, TLS 1.3 in transit. ISO 27001 certified. No third-party sharing without consent.',
    policy: 'Data sharing requires explicit consent. Privacy managed in Account → Privacy.',
    sentiment: 'Neutral → reassured.',
    tip: 'Privacy-sensitive customer. Be thorough and offer Privacy settings path.',
    reply1: 'Hi Carlos! We use AES-256 encryption and TLS 1.3 — your data is never shared without your consent.',
    action: 'Send data security documentation link to customer.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'Your data is safe with us, Carlos.<br><br>🔒 AES-256 encryption at rest<br>🔒 TLS 1.3 in transit<br>🏢 ISO 27001 certified infrastructure<br><br>Manage all sharing preferences in Account → Privacy. Anything else?',
  },
  'Julia Chen': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer asking how to report a technical issue, including when the app won\'t open.',
    intent: 'Technical Issue Reporting.',
    facts: 'In-app: Help → Report a Problem. If app won\'t open: email bugs@clarity.com with device info.',
    policy: 'Bug reports via in-app tool or bugs@clarity.com. Include device model and OS version.',
    sentiment: 'Neutral → helped.',
    tip: 'Cover both scenarios: app working and app crashed.',
    reply1: 'Hi Julia! Use Help → Report a Problem in the app, or email bugs@clarity.com if it won\'t open.',
    action: 'Check if issue needs escalation to the engineering team.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'Thanks for reaching out, Julia!<br><br>To report from the app: Help → Report a Problem (logs auto-attach).<br><br>If the app won\'t open: email bugs@clarity.com with your device model and OS version.<br><br>We\'ll prioritise it — let us know how it goes!',
  },
  'Brandon Smith': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer asking about free trial features and whether a credit card is required.',
    intent: 'Free Trial Inquiry.',
    facts: '14-day Pro trial. No credit card required. All Pro features included.',
    policy: 'Trial includes all Pro features for 14 days. No payment info required at sign-up.',
    sentiment: 'Curious → interested.',
    tip: 'High conversion potential. Highlight the no-credit-card benefit prominently.',
    reply1: 'Hi Brandon! Our 14-day trial includes all Pro features — and no credit card is needed.',
    action: 'Offer direct sign-up link and mark as trial prospect in CRM.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'The free trial has everything, Brandon:<br><br>✅ Unlimited transactions<br>✅ Multi-currency support<br>✅ Analytics & priority support<br>✅ No credit card required<br><br>Sign up with your email and you\'re in for 14 days. Want a direct link?',
  },
  'Nina Brown': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer wants to change email but no longer has access to their old address.',
    intent: 'Email Address Change — No Old Email Access.',
    facts: 'Standard flow requires old + new email verification. Alternative: phone or government ID.',
    policy: 'Identity verification via phone or ID can bypass old email verification requirement.',
    sentiment: 'Concerned → pending resolution.',
    tip: 'Escalate if phone verification also fails. Require ID as final fallback.',
    reply1: 'Hi Nina! I can verify your identity via phone number or ID — no need for your old email.',
    action: 'Initiate alternative identity verification process for email change.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'No problem, Nina — we can work around that!<br><br>To verify your identity, I\'ll need either:<br>• Your phone number on file, or<br>• A copy of your government-issued ID<br><br>Which works best for you?',
  },
  'Oliver Johnson': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer asking about direct contact options and business account benefits.',
    intent: 'Customer Service & Business Account Inquiry.',
    facts: 'Live chat 24/7, phone, email. Business/Enterprise plans include a dedicated account manager.',
    policy: 'Business and Enterprise plans include dedicated account manager and faster SLAs.',
    sentiment: 'Neutral → interested in upgrade.',
    tip: 'Potential upsell opportunity. Customer is probing business account perks.',
    reply1: 'Hi Oliver! You can reach us 24/7 via chat, phone at +1 800 123 4567, or support@clarity.com.',
    action: 'Present Business plan upgrade options with dedicated account manager details.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'Business and Enterprise plans come with a dedicated account manager, Oliver!<br><br>That means direct access, faster resolutions, and proactive support.<br><br>Would you like me to share our Business plan details or connect you with our sales team?',
  },
  'Grace White': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer can\'t log in — account not found when using email address.',
    intent: 'Account Recovery — Unknown Email.',
    facts: 'Login attempted but account not found. May have registered with a different email.',
    policy: 'Account lookup available via phone number. Identity verification required.',
    sentiment: 'Frustrated → in progress.',
    tip: 'May have multiple accounts or a different email. Use phone lookup as next step.',
    reply1: 'Hi Grace! Your account might be under a different email — I can look you up by phone number.',
    action: 'Run account lookup by phone number.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'Let me search by your phone number instead.<br><br>If there\'s a match, I\'ll send a password reset to the registered email so you can regain access.<br><br>What\'s the phone number you may have used when signing up?',
  },
  'Leo Thompson': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer asking about current promotions and whether they apply to upgrades.',
    intent: 'Promotion & Discount Inquiry.',
    facts: '20% off annual plans. Code CLARITY20. Applies to new subscriptions and upgrades. Expires end of month.',
    policy: 'Promo code CLARITY20 valid for annual plans, new and upgrades. Expires end of current month.',
    sentiment: 'Curious → excited → converting.',
    tip: 'High-intent customer ready to upgrade. Confirm discount applies and close.',
    reply1: 'Hi Leo! Yes — use code CLARITY20 for 20% off any annual plan, including upgrades!',
    action: 'Confirm promo code CLARITY20 and guide customer to upgrade flow.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'The 20% discount applies to your upgrade, Leo!<br><br>🎉 Code: CLARITY20<br>📅 Expires the 30th<br><br>Go to Account → Subscription → Change Plan and enter the code at checkout. Enjoy the savings!',
  },
  'Emma Garcia': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer asking about returns policy and reporting a potential duplicate charge.',
    intent: 'Returns Policy & Billing Dispute.',
    facts: '30-day money-back guarantee. Potential duplicate charge reported — needs investigation.',
    policy: '30-day full refund, no questions asked. Duplicate charges refunded immediately upon verification.',
    sentiment: 'Concerned → awaiting resolution.',
    tip: 'Possible billing error — high priority. Collect account email and escalate to billing team.',
    reply1: 'Hi Emma! We offer a 30-day money-back guarantee. If there\'s a duplicate charge, I\'ll look into it now.',
    action: 'Investigate duplicate charge on customer account and escalate to billing if confirmed.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'I\'ve flagged the potential duplicate charge for review, Emma.<br><br>If confirmed, your refund will be processed immediately — usually within 1–3 business days.<br><br>I\'ll follow up as soon as our billing team confirms. Sorry for the inconvenience!',
  },
  'Liam Johnson': {
    reasoning1: 'Here is the ticket summary:',
    summary: 'Customer not receiving order tracking emails despite notifications being enabled.',
    intent: 'Order Tracking — Missing Email Notifications.',
    facts: 'Notifications enabled but emails not received. Manual resend available.',
    policy: 'Tracking emails triggered automatically. Agent can manually resend if not received.',
    sentiment: 'Concerned → reassured.',
    tip: 'Check delivery logs. Possible spam filtering. Resend manually and escalate if persists.',
    reply1: 'Hi Liam! Your notifications look enabled — let me resend the tracking email now.',
    action: 'Manually resend order tracking email and review delivery logs.',
    reasoning2: 'Here is the suggested reply:',
    reply2: 'I\'ve resent the tracking email to your address, Liam.<br><br>Please check your inbox in the next few minutes — and your spam folder just in case.<br><br>You can also track directly at Account → Orders → Track.<br><br>Let me know if it doesn\'t come through!',
  },
};

// ── Details data ───────────────────────────────────────────
const detailsData = {
  'Caroline Brennan': {
    contact:       { name: 'Caroline Brennan', phone: '+351 918 273 721', email: 'caroline.brennan@email.com', tags: [{ label: 'Free plan', color: '#4061d8' }, { label: 'Low Value', color: '#7c3aed' }], externalId: null },
    ticket:        { id: '#864',  assignee: { initials: 'JW', name: 'Jamie Wilson',    bg: 'var(--utilities-surface-bluesubtle)',   color: 'var(--utilities-content-onsoft-blue)'   }, teamInbox: null,         status: 'open',    tags: [],                                            category: 'Payments & Top-up',       priority: 'critical' },
    recentTickets: [
      { status: 'closed', date: '18 Dec', preview: 'My card was declined at checkout' },
      { status: 'closed', date: '3 Nov',  preview: "I can't find my transaction history" },
    ],
  },
  'Ethan Kim': {
    contact:       { name: 'Ethan Kim',        phone: '+1 415 555 0123',   email: 'ethan.kim@email.com',        tags: [{ label: 'Pro plan', color: '#22c55e' }],                                                  externalId: 'EK-2891' },
    ticket:        { id: '#921',  assignee: { initials: 'MT', name: 'Marcus Taylor',   bg: 'var(--utilities-surface-cyansubtle)',   color: 'var(--utilities-content-onsoft-cyan)'   }, teamInbox: 'Support',    status: 'open',    tags: [{ label: 'Feature',  color: '#4061d8' }],  category: 'Payment Methods',         priority: 'medium'   },
    recentTickets: [
      { status: 'closed', date: '10 Dec', preview: 'How do I add a second card?' },
      { status: 'closed', date: '22 Nov', preview: 'Payment failed on subscription renewal' },
      { status: 'closed', date: '5 Oct',  preview: 'Can I pay in multiple currencies?' },
    ],
  },
  'Jason Lee': {
    contact:       { name: 'Jason Lee',        phone: '+44 20 7946 0958',  email: 'jason.lee@email.com',        tags: [],                                                                                        externalId: 'JL-5024' },
    ticket:        { id: '#745',  assignee: { initials: 'ED', name: 'Emma Davis',      bg: 'var(--utilities-surface-orangesubtle)', color: 'var(--utilities-content-onsoft-orange)' }, teamInbox: 'Support',    status: 'pending', tags: [],                                            category: 'Support Channels',        priority: 'low'      },
    recentTickets: [
      { status: 'closed', date: '8 Jan',  preview: 'Where can I find your phone number?' },
    ],
  },
  'Aisha Patel': {
    contact:       { name: 'Aisha Patel',      phone: '+91 98765 43210',   email: 'aisha.patel@email.com',      tags: [{ label: 'VIP',      color: '#f59e0b' }],                                                  externalId: null      },
    ticket:        { id: '#1203', assignee: { initials: 'JC', name: 'James Carter',    bg: 'var(--utilities-surface-purplesubtle)', color: 'var(--utilities-content-onsoft-purple)' }, teamInbox: null,         status: 'open',    tags: [],                                            category: 'Account Verification',    priority: 'high'     },
    recentTickets: [
      { status: 'closed', date: '2 Jan',  preview: 'Verification email not received' },
      { status: 'closed', date: '15 Dec', preview: "My ID upload isn't working" },
    ],
  },
  'Marcus Wu': {
    contact:       { name: 'Marcus Wu',        phone: '+1 312 555 0198',   email: 'marcus.wu@email.com',        tags: [{ label: 'Pro plan', color: '#22c55e' }, { label: 'High Value', color: '#f59e0b' }],       externalId: 'MW-4418' },
    ticket:        { id: '#1089', assignee: null,                                                                                                                                                                   teamInbox: null,         status: 'open',    tags: [],                                            category: 'Subscription & Billing',  priority: 'medium'   },
    recentTickets: [
      { status: 'closed', date: '20 Dec', preview: 'Upgrade to Business plan' },
      { status: 'closed', date: '1 Dec',  preview: 'Double charge on my account' },
      { status: 'closed', date: '14 Nov', preview: 'Annual billing vs monthly question' },
    ],
  },
  'Linda Gomez': {
    contact:       { name: 'Linda Gomez',      phone: '+34 91 555 2233',   email: 'linda.gomez@email.com',      tags: [{ label: 'Free plan', color: '#4061d8' }],                                                 externalId: null      },
    ticket:        { id: '#782',  assignee: { initials: 'SA', name: 'Sofia Almeida',   bg: 'var(--utilities-surface-pinksubtle)',   color: 'var(--utilities-content-onsoft-pink)'   }, teamInbox: null,         status: 'pending', tags: [],                                            category: 'Account Access',          priority: 'high'     },
    recentTickets: [
      { status: 'closed', date: '12 Jan', preview: 'Email change not going through' },
    ],
  },
  'Carlos Rodriguez': {
    contact:       { name: 'Carlos Rodriguez', phone: '+52 55 5555 1234',  email: 'carlos.rodriguez@email.com', tags: [{ label: 'Enterprise', color: '#7c3aed' }],                                                externalId: 'CR-3309' },
    ticket:        { id: '#534',  assignee: { initials: 'DP', name: 'David Park',      bg: 'var(--utilities-surface-bluesubtle)',   color: 'var(--utilities-content-onsoft-blue)'   }, teamInbox: 'Enterprise', status: 'snoozed', tags: [{ label: 'Security',  color: '#ef4444' }],  category: 'Data & Privacy',          priority: 'low'      },
    recentTickets: [
      { status: 'closed', date: '29 Dec', preview: 'Request for GDPR data export' },
      { status: 'closed', date: '10 Dec', preview: 'Team member access permissions' },
    ],
  },
  'Julia Chen': {
    contact:       { name: 'Julia Chen',       phone: '+86 138 0013 8000', email: 'julia.chen@email.com',       tags: [],                                                                                        externalId: null      },
    ticket:        { id: '#1156', assignee: null,                                                                                                                                                                   teamInbox: null,         status: 'open',    tags: [{ label: 'Bug',      color: '#ef4444' }],  category: 'Technical Issues',        priority: 'high'     },
    recentTickets: [
      { status: 'closed', date: '5 Jan',  preview: 'App crashes on transfer screen' },
      { status: 'closed', date: '18 Dec', preview: 'Notifications not working on iOS' },
    ],
  },
  'Brandon Smith': {
    contact:       { name: 'Brandon Smith',    phone: '+1 206 555 0144',   email: 'brandon.smith@email.com',    tags: [{ label: 'Trial',    color: '#22c55e' }],                                                  externalId: null      },
    ticket:        { id: '#998',  assignee: { initials: 'RT', name: 'Ryan Thompson',   bg: 'var(--utilities-surface-cyansubtle)',   color: 'var(--utilities-content-onsoft-cyan)'   }, teamInbox: null,         status: 'open',    tags: [],                                            category: 'Plans & Pricing',         priority: 'medium'   },
    recentTickets: [
      { status: 'closed', date: '3 Jan',  preview: 'What happens after the trial ends?' },
    ],
  },
  'Nina Brown': {
    contact:       { name: 'Nina Brown',       phone: '+44 7700 900123',   email: 'nina.brown@email.com',       tags: [{ label: 'Free plan', color: '#4061d8' }],                                                 externalId: 'NB-8821' },
    ticket:        { id: '#1044', assignee: { initials: 'AL', name: 'Anna Lee',        bg: 'var(--utilities-surface-pinksubtle)',   color: 'var(--utilities-content-onsoft-pink)'   }, teamInbox: null,         status: 'snoozed', tags: [],                                            category: 'Account Management',      priority: 'low'      },
    recentTickets: [
      { status: 'closed', date: '7 Jan',  preview: 'How to merge two accounts?' },
      { status: 'closed', date: '22 Dec', preview: 'Change linked phone number' },
    ],
  },
  'Oliver Johnson': {
    contact:       { name: 'Oliver Johnson',   phone: '+1 650 555 0178',   email: 'oliver.johnson@email.com',   tags: [{ label: 'Business', color: '#7c3aed' }, { label: 'High Value', color: '#f59e0b' }],       externalId: 'OJ-6612' },
    ticket:        { id: '#677',  assignee: null,                                                                                                                                                                   teamInbox: null,         status: 'open',    tags: [{ label: 'Upsell',   color: '#22c55e' }],  category: 'Customer Service',        priority: 'medium'   },
    recentTickets: [
      { status: 'closed', date: '9 Jan',  preview: 'Interested in the Enterprise plan' },
      { status: 'closed', date: '14 Dec', preview: 'API rate limits too low for our usage' },
      { status: 'closed', date: '28 Nov', preview: 'Need dedicated account manager' },
    ],
  },
  'Grace White': {
    contact:       { name: 'Grace White',      phone: '+1 303 555 0192',   email: 'grace.white@email.com',      tags: [],                                                                                        externalId: null      },
    ticket:        { id: '#823',  assignee: { initials: 'MB', name: 'Matt Brown',      bg: 'var(--utilities-surface-orangesubtle)', color: 'var(--utilities-content-onsoft-orange)' }, teamInbox: 'Support',    status: 'closed',  tags: [],                                            category: 'Account Recovery',        priority: 'low'      },
    recentTickets: [
      { status: 'closed', date: '11 Jan', preview: 'Lost access to authenticator app' },
    ],
  },
  'Leo Thompson': {
    contact:       { name: 'Leo Thompson',     phone: '+1 512 555 0137',   email: 'leo.thompson@email.com',     tags: [{ label: 'Annual plan', color: '#22c55e' }],                                               externalId: null      },
    ticket:        { id: '#1342', assignee: { initials: 'KW', name: 'Kate Wilson',     bg: 'var(--utilities-surface-purplesubtle)', color: 'var(--utilities-content-onsoft-purple)' }, teamInbox: null,         status: 'closed',  tags: [],                                            category: 'Promotions & Discounts',  priority: 'low'      },
    recentTickets: [
      { status: 'closed', date: '4 Jan',  preview: 'Referral code not applying discount' },
      { status: 'closed', date: '19 Dec', preview: 'Black Friday promo not working' },
    ],
  },
  'Emma Garcia': {
    contact:       { name: 'Emma Garcia',      phone: '+34 93 555 4455',   email: 'emma.garcia@email.com',      tags: [{ label: 'Pro plan', color: '#22c55e' }],                                                  externalId: 'EG-7743' },
    ticket:        { id: '#1455', assignee: { initials: 'LF', name: 'Lucas Ferreira',  bg: 'var(--utilities-surface-bluesubtle)',   color: 'var(--utilities-content-onsoft-blue)'   }, teamInbox: 'Billing',    status: 'open',    tags: [{ label: 'Billing',  color: '#ef4444' }],  category: 'Billing & Refunds',       priority: 'critical' },
    recentTickets: [
      { status: 'closed', date: '6 Jan',  preview: 'Incorrect charge on December invoice' },
      { status: 'closed', date: '21 Dec', preview: 'Refund request for cancelled subscription' },
      { status: 'closed', date: '9 Dec',  preview: 'VAT number not showing on invoice' },
    ],
  },
  'Liam Johnson': {
    contact:       { name: 'Liam Johnson',     phone: '+1 404 555 0186',   email: 'liam.johnson@email.com',     tags: [],                                                                                        externalId: null      },
    ticket:        { id: '#889',  assignee: { initials: 'CM', name: 'Chris Murphy',    bg: 'var(--utilities-surface-cyansubtle)',   color: 'var(--utilities-content-onsoft-cyan)'   }, teamInbox: 'Support',    status: 'closed',  tags: [],                                            category: 'Order Tracking',          priority: 'low'      },
    recentTickets: [
      { status: 'closed', date: '13 Jan', preview: 'Where is my order? Been 5 days' },
      { status: 'closed', date: '2 Jan',  preview: 'Wrong item delivered' },
    ],
  },
};

// ── View labels ────────────────────────────────────────────
const VIEW_LABELS = {
  assigned:   'Assigned to me',
  mentions:   'Mentions',
  unassigned: 'Unassigned',
  snoozed:    'Snoozed',
  closed:     'Closed',
  all:        'All',
};
